# tests/test_codex_protocol.py
"""The generated codex models: pinned to the tested codex version and
proven against live-captured app-server lines."""
import json
from pathlib import Path

import pytest

from tandem.compat import COMPAT

GOLDEN = Path(__file__).parent / "golden" / "chat" / "codex_appserver.jsonl"

NOTIFICATIONS = {
    "item/started": "ItemStartedNotification",
    "item/completed": "ItemCompletedNotification",
    "item/agentMessage/delta": "AgentMessageDeltaNotification",
    "turn/started": "TurnStartedNotification",
    "turn/completed": "TurnCompletedNotification",
    "thread/tokenUsage/updated": "ThreadTokenUsageUpdatedNotification",
    "account/rateLimits/updated": "AccountRateLimitsUpdatedNotification",
    "item/commandExecution/requestApproval": "CommandExecutionRequestApprovalParams",
}


@pytest.fixture(scope="module")
def cp():
    from tandem.chat.runtime import codex_protocol
    return codex_protocol


def test_header_pins_the_tested_codex_version(cp):
    first = Path(cp.__file__).read_text().splitlines()[0]
    assert first.startswith("# generated by tools/gen_codex_protocol.py from codex ")
    assert f"from codex {COMPAT['codex'].tested} " in first


def test_every_golden_line_validates(cp):
    seen = set()
    for line in GOLDEN.read_text().splitlines():
        m = json.loads(line)
        method = m.get("method")
        if method in NOTIFICATIONS:
            getattr(cp, NOTIFICATIONS[method]).model_validate(m["params"])
            seen.add(method)
        elif m.get("id") == 1:
            cp.InitializeResponse.model_validate(m["result"])
        elif m.get("id") == 2:
            r = cp.ThreadResumeResponse.model_validate(m["result"])
            assert r.thread.id == "01a0774c-fdd8-7937-a3dd-ba15c718b01a"
        elif m.get("id") == 3:
            cp.TurnStartResponse.model_validate(m["result"])
    assert seen == set(NOTIFICATIONS)


def test_item_discriminator_is_readable(cp):
    types = []
    for line in GOLDEN.read_text().splitlines():
        m = json.loads(line)
        if m.get("method") == "item/started":
            n = cp.ItemStartedNotification.model_validate(m["params"])
            item = getattr(n.item, "root", n.item)
            types.append(item.type)
    assert types == ["userMessage", "reasoning", "commandExecution", "agentMessage"]


def test_requests_dump_on_the_wire_shape(cp):
    p = cp.TurnStartParams(threadId="t", input=[{"type": "text", "text": "hi"}])
    assert p.model_dump(by_alias=True, exclude_none=True) == {
        "threadId": "t", "input": [{"type": "text", "text": "hi", "text_elements": []}]}
    assert cp.CommandExecutionRequestApprovalResponse(decision="accept").model_dump() == {"decision": "accept"}
    assert cp.ThreadStartParams(cwd="/x").model_dump(by_alias=True, exclude_none=True) == {"cwd": "/x"}


def test_unknown_fields_are_ignored(cp):
    cp.AgentMessageDeltaNotification.model_validate(
        {"threadId": "t", "turnId": "u", "itemId": "i", "delta": "x", "futureField": 1})
