# generated by tools/gen_codex_protocol.py from codex 0.153.4 (schema sha256 bbb2e50b870d) — do not edit
# ruff: noqa
# generated by datamodel-codegen:
#   filename:  merged.json

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Granular(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    mcp_elicitations: bool
    request_permissions: bool | None = False
    rules: bool
    sandbox_approval: bool
    skill_approval: bool | None = False


class AskForApproval1(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    granular: Granular


class ByteRange(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    end: Annotated[int, Field(ge=0)]
    start: Annotated[int, Field(ge=0)]


class ClientInfo(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    name: str
    title: str | None = None
    version: str


class FunctionCallOutputContentItem1(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    text: str
    type: Annotated[
        Literal['input_text'], Field(title='InputTextFunctionCallOutputContentItemType')
    ]


class FunctionCallOutputContentItem3(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    audio_url: str
    type: Annotated[
        Literal['input_audio'],
        Field(title='InputAudioFunctionCallOutputContentItemType'),
    ]


class FunctionCallOutputContentItem4(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    encrypted_content: str
    type: Annotated[
        Literal['encrypted_content'],
        Field(title='EncryptedContentFunctionCallOutputContentItemType'),
    ]


class InitializeCapabilities(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    experimentalApi: Annotated[
        bool | None,
        Field(description='Opt into receiving experimental API methods and fields.'),
    ] = False
    extensions: Annotated[
        dict[str, Any] | None,
        Field(description='MCP extension settings declared by the app-server client.'),
    ] = None
    mcpServerOpenaiFormElicitation: Annotated[
        bool | None,
        Field(
            description='Legacy opt-in for the `openai/form` MCP extension.\n\nNew clients should declare `openai/form` in [`Self::extensions`].'
        ),
    ] = None
    optOutNotificationMethods: Annotated[
        list[str] | None,
        Field(
            description='Exact notification method names that should be suppressed for this connection (for example `thread/started`).'
        ),
    ] = None
    requestAttestation: Annotated[
        bool | None,
        Field(
            description='Opt into `attestation/generate` requests for upstream `x-oai-attestation`.'
        ),
    ] = False


class InitializeParams(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    capabilities: InitializeCapabilities | None = None
    clientInfo: ClientInfo


class ReasoningEffort(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description='A non-empty reasoning effort value advertised by the model.',
            min_length=1,
        ),
    ]


class SandboxPolicy1(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: Annotated[
        Literal['dangerFullAccess'], Field(title='DangerFullAccessSandboxPolicyType')
    ]


class SandboxPolicy2(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    networkAccess: bool | None = False
    type: Annotated[Literal['readOnly'], Field(title='ReadOnlySandboxPolicyType')]


class SandboxPolicy3(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    networkAccess: Literal['restricted', 'enabled'] | None = 'restricted'
    type: Annotated[
        Literal['externalSandbox'], Field(title='ExternalSandboxSandboxPolicyType')
    ]


class SandboxPolicy4(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    excludeSlashTmp: bool | None = False
    excludeTmpdirEnvVar: bool | None = False
    networkAccess: bool | None = False
    type: Annotated[
        Literal['workspaceWrite'], Field(title='WorkspaceWriteSandboxPolicyType')
    ]
    writableRoots: list[str] | None = []


class TextElement(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    byteRange: Annotated[
        ByteRange,
        Field(
            description='Byte range in the parent `text` buffer that this element occupies.'
        ),
    ]
    placeholder: Annotated[
        str | None,
        Field(
            description='Optional human-readable placeholder for the element, displayed in the UI.'
        ),
    ] = None


class ThreadResumeParams(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    approvalPolicy: (
        Literal['untrusted', 'on-request', 'never'] | AskForApproval1 | None
    ) = None
    approvalsReviewer: Annotated[
        Literal['user', 'auto_review', 'guardian_subagent'] | None,
        Field(
            description='Override where approval requests are routed for review on this thread and subsequent turns.'
        ),
    ] = None
    baseInstructions: str | None = None
    config: dict[str, Any] | None = None
    cwd: str | None = None
    developerInstructions: str | None = None
    excludeTurns: Annotated[
        bool | None,
        Field(
            description='When true, return only thread metadata and live-resume state without populating `thread.turns`. This is useful when the client plans to call `thread/turns/list` immediately after resuming. Full-history hydration is deprecated for paginated threads; use this with `thread/turns/list` and `thread/items/list` instead.'
        ),
    ] = None
    model: Annotated[
        str | None,
        Field(description='Configuration overrides for the resumed thread, if any.'),
    ] = None
    modelProvider: str | None = None
    personality: Literal['none', 'friendly', 'pragmatic'] | None = None
    sandbox: Literal['read-only', 'workspace-write', 'danger-full-access'] | None = None
    serviceTier: str | None = None
    threadId: str


class ThreadSectionAppearance(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    color: str | None = None
    icon: str | None = None


class TurnInterruptParams(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    threadId: str
    turnId: str


class UserInput1(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    text: str
    text_elements: Annotated[
        list[TextElement] | None,
        Field(
            description='UI-defined spans within `text` used to render or persist special elements.',
            validate_default=True,
        ),
    ] = []
    type: Annotated[Literal['text'], Field(title='TextUserInputType')]


class UserInput2(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    detail: Literal['auto', 'low', 'high', 'original'] | None = None
    type: Annotated[Literal['image'], Field(title='ImageUserInputType')]
    url: str


class UserInput3(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    detail: Literal['auto', 'low', 'high', 'original'] | None = None
    path: str
    type: Annotated[Literal['localImage'], Field(title='LocalImageUserInputType')]


class UserInput4(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: Annotated[Literal['audio'], Field(title='AudioUserInputType')]
    url: str


class UserInput5(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    path: str
    type: Annotated[Literal['localAudio'], Field(title='LocalAudioUserInputType')]


class UserInput6(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    name: str
    path: str
    type: Annotated[Literal['skill'], Field(title='SkillUserInputType')]


class UserInput7(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    name: str
    path: str
    type: Annotated[Literal['mention'], Field(title='MentionUserInputType')]


class AdditionalNetworkPermissions(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    enabled: bool | None = None


class CommandAction1(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    command: str
    name: str
    path: str
    type: Annotated[Literal['read'], Field(title='ReadCommandActionType')]


class CommandAction2(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    command: str
    path: str | None = None
    type: Annotated[Literal['listFiles'], Field(title='ListFilesCommandActionType')]


class CommandAction3(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    command: str
    path: str | None = None
    query: str | None = None
    type: Annotated[Literal['search'], Field(title='SearchCommandActionType')]


class CommandAction4(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    command: str
    type: Annotated[Literal['unknown'], Field(title='UnknownCommandActionType')]


class AcceptWithExecpolicyAmendment(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    execpolicy_amendment: list[str]


class CommandExecutionApprovalDecision1(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    acceptWithExecpolicyAmendment: AcceptWithExecpolicyAmendment


class FileSystemPath1(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    path: str
    type: Annotated[Literal['path'], Field(title='PathFileSystemPathType')]


class FileSystemPath2(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    pattern: str
    type: Annotated[
        Literal['glob_pattern'], Field(title='GlobPatternFileSystemPathType')
    ]


class FileSystemSpecialPath1(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    kind: Literal['root']


class FileSystemSpecialPath2(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    kind: Literal['minimal']


class FileSystemSpecialPath3(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    kind: Literal['project_roots']
    subpath: str | None = None


class FileSystemSpecialPath4(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    kind: Literal['tmpdir']


class FileSystemSpecialPath5(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    kind: Literal['slash_tmp']


class FileSystemSpecialPath6(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    kind: Literal['unknown']
    path: str
    subpath: str | None = None


class DynamicToolCallOutputContentItem1(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    text: str
    type: Annotated[
        Literal['inputText'],
        Field(title='InputTextDynamicToolCallOutputContentItemType'),
    ]


class DynamicToolCallOutputContentItem2(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    imageUrl: str
    type: Annotated[
        Literal['inputImage'],
        Field(title='InputImageDynamicToolCallOutputContentItemType'),
    ]


class DynamicToolCallOutputContentItem3(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    audioUrl: str
    type: Annotated[
        Literal['inputAudio'],
        Field(title='InputAudioDynamicToolCallOutputContentItemType'),
    ]


class FileChangeRequestApprovalParams(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    grantRoot: Annotated[
        str | None,
        Field(
            description='[UNSTABLE] When set, the agent is asking the user to allow writes under this root for the remainder of the session (unclear if this is honored today).'
        ),
    ] = None
    itemId: str
    reason: Annotated[
        str | None,
        Field(
            description='Optional explanatory reason (e.g. request for extra write access).'
        ),
    ] = None
    startedAtMs: Annotated[
        int,
        Field(
            description='Unix timestamp (in milliseconds) when this approval request started.'
        ),
    ]
    threadId: str
    turnId: str


class FileChangeRequestApprovalResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    decision: (
        Literal['accept']
        | Literal['acceptForSession']
        | Literal['decline']
        | Literal['cancel']
    )


class AgentMessageDeltaNotification(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    delta: str
    itemId: str
    threadId: str
    turnId: str


class AsyncUserInputQuestion(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    options: list[str] | None = None
    title: str


class HttpConnectionFailed(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    httpStatusCode: Annotated[int | None, Field(ge=0)] = None


class CodexErrorInfo1(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    httpConnectionFailed: HttpConnectionFailed


class ResponseStreamConnectionFailed(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    httpStatusCode: Annotated[int | None, Field(ge=0)] = None


class CodexErrorInfo2(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    responseStreamConnectionFailed: ResponseStreamConnectionFailed


class ResponseStreamDisconnected(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    httpStatusCode: Annotated[int | None, Field(ge=0)] = None


class CodexErrorInfo3(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    responseStreamDisconnected: ResponseStreamDisconnected


class ResponseTooManyFailedAttempts(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    httpStatusCode: Annotated[int | None, Field(ge=0)] = None


class CodexErrorInfo4(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    responseTooManyFailedAttempts: ResponseTooManyFailedAttempts


class CommandExecutionOutputDeltaNotification(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    delta: str
    itemId: str
    threadId: str
    turnId: str


class CreditsSnapshot(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    balance: str | None = None
    hasCredits: bool
    unlimited: bool


class FileChangeOutputDeltaNotification(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    delta: str
    itemId: str
    threadId: str
    turnId: str


class GitInfo(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    branch: str | None = None
    originUrl: str | None = None
    sha: str | None = None


class HookPromptFragment(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    hookRunId: str
    text: str


class ImageGenerationFailure1(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    limitId: str
    resetsAt: int | None = None
    type: Annotated[
        Literal['usageLimitExceeded'],
        Field(title='UsageLimitExceededImageGenerationFailureType'),
    ]


class ImageGenerationFailure(RootModel[ImageGenerationFailure1]):
    root: ImageGenerationFailure1


class McpToolCallAppContext(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    actionName: str | None = None
    appName: str | None = None
    connectorId: str
    linkId: str | None = None
    resourceUri: str | None = None


class McpToolCallError(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    message: str


class McpToolCallResult(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    field_meta: Annotated[Any | None, Field(alias='_meta')] = None
    content: list[Any]
    structuredContent: Any | None = None


class MemoryCitationEntry(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    lineEnd: Annotated[int, Field(ge=0)]
    lineStart: Annotated[int, Field(ge=0)]
    note: str
    path: str


class MisalignmentSteer(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    message: str


class PatchChangeKind1(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: Annotated[Literal['add'], Field(title='AddPatchChangeKindType')]


class PatchChangeKind2(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: Annotated[Literal['delete'], Field(title='DeletePatchChangeKindType')]


class PatchChangeKind3(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    move_path: str | None = None
    type: Annotated[Literal['update'], Field(title='UpdatePatchChangeKindType')]


class RateLimitWindow(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    resetsAt: int | None = None
    usedPercent: int
    windowDurationMins: int | None = None


class ReasoningSummaryTextDeltaNotification(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    delta: str
    itemId: str
    summaryIndex: int
    threadId: str
    turnId: str


class SessionSource1(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    custom: str


class SpendControlLimitSnapshot(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    limit: str
    remainingPercent: int
    resetsAt: int
    used: str


class ThreadSpawn(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    agent_nickname: str | None = None
    agent_path: str | None = None
    agent_role: str | None = None
    depth: int
    parent_thread_id: str


class SubAgentSource1(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    thread_spawn: ThreadSpawn


class SubAgentSource2(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    other: str


class ThreadItem1(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    clientId: str | None = None
    content: list[
        UserInput1
        | UserInput2
        | UserInput3
        | UserInput4
        | UserInput5
        | UserInput6
        | UserInput7
    ]
    id: str
    type: Annotated[Literal['userMessage'], Field(title='UserMessageThreadItemType')]


class ThreadItem2(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    fragments: list[HookPromptFragment]
    id: str
    type: Annotated[Literal['hookPrompt'], Field(title='HookPromptThreadItemType')]


class ThreadItem5(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    id: str
    text: str
    type: Annotated[Literal['plan'], Field(title='PlanThreadItemType')]


class ThreadItem6(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    content: list[str] | None = []
    id: str
    summary: list[str] | None = []
    type: Annotated[Literal['reasoning'], Field(title='ReasoningThreadItemType')]


class ThreadItem7(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    aggregatedOutput: Annotated[
        str | None,
        Field(description="The command's output, aggregated from stdout and stderr."),
    ] = None
    command: Annotated[str, Field(description='The command to be executed.')]
    commandActions: Annotated[
        list[CommandAction1 | CommandAction2 | CommandAction3 | CommandAction4],
        Field(
            description='A best-effort parsing of the command to understand the action(s) it will perform. This returns a list of CommandAction objects because a single shell command may be composed of many commands piped together.'
        ),
    ]
    cwd: Annotated[str, Field(description="The command's working directory.")]
    durationMs: Annotated[
        int | None,
        Field(description='The duration of the command execution in milliseconds.'),
    ] = None
    exitCode: Annotated[int | None, Field(description="The command's exit code.")] = (
        None
    )
    id: str
    pluginId: Annotated[
        str | None,
        Field(
            description='Trusted first-party plugin id when this command resolves to one plugin script.'
        ),
    ] = None
    processId: Annotated[
        str | None,
        Field(
            description='Identifier for the underlying PTY process (when available).'
        ),
    ] = None
    scriptPath: Annotated[
        str | None,
        Field(
            description='Safe plugin-relative path when this command resolves to one plugin script.'
        ),
    ] = None
    source: (
        Literal['agent', 'userShell', 'unifiedExecStartup', 'unifiedExecInteraction']
        | None
    ) = 'agent'
    status: Literal['inProgress', 'completed', 'failed', 'declined']
    type: Annotated[
        Literal['commandExecution'], Field(title='CommandExecutionThreadItemType')
    ]


class ThreadItem9(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    appContext: McpToolCallAppContext | None = None
    arguments: Any
    durationMs: Annotated[
        int | None,
        Field(description='The duration of the MCP tool call in milliseconds.'),
    ] = None
    error: McpToolCallError | None = None
    id: str
    mcpAppResourceUri: Annotated[
        str | None,
        Field(description='Deprecated: use `appContext.resourceUri` instead.'),
    ] = None
    pluginId: str | None = None
    readOnlyHint: bool | None = None
    result: McpToolCallResult | None = None
    server: str
    status: Literal['inProgress', 'completed', 'failed']
    tool: str
    type: Annotated[Literal['mcpToolCall'], Field(title='McpToolCallThreadItemType')]


class ThreadItem10(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    arguments: Any
    contentItems: (
        list[
            DynamicToolCallOutputContentItem1
            | DynamicToolCallOutputContentItem2
            | DynamicToolCallOutputContentItem3
        ]
        | None
    ) = None
    durationMs: Annotated[
        int | None,
        Field(description='The duration of the dynamic tool call in milliseconds.'),
    ] = None
    id: str
    namespace: str | None = None
    status: Literal['inProgress', 'completed', 'failed']
    success: bool | None = None
    tool: str
    type: Annotated[
        Literal['dynamicToolCall'], Field(title='DynamicToolCallThreadItemType')
    ]


class ThreadItem12(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    agentPath: str
    agentThreadId: str
    id: str
    kind: Literal['started', 'interacted', 'interrupted', 'completed']
    type: Annotated[
        Literal['subAgentActivity'], Field(title='SubAgentActivityThreadItemType')
    ]


class ThreadItem14(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    id: str
    path: str
    type: Annotated[Literal['imageView'], Field(title='ImageViewThreadItemType')]


class ThreadItem15(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    durationMs: Annotated[int, Field(ge=0)]
    id: str
    type: Annotated[Literal['sleep'], Field(title='SleepThreadItemType')]


class ThreadItem16(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    failure: ImageGenerationFailure | None = None
    id: str
    result: str
    revisedPrompt: str | None = None
    savedPath: str | None = None
    status: str
    transparentBackground: bool | None = None
    type: Annotated[
        Literal['imageGeneration'], Field(title='ImageGenerationThreadItemType')
    ]


class ThreadItem17(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    id: str
    review: str
    type: Annotated[
        Literal['enteredReviewMode'], Field(title='EnteredReviewModeThreadItemType')
    ]


class ThreadItem18(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    id: str
    review: str
    type: Annotated[
        Literal['exitedReviewMode'], Field(title='ExitedReviewModeThreadItemType')
    ]


class ThreadItem19(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    id: str
    type: Annotated[
        Literal['contextCompaction'], Field(title='ContextCompactionThreadItemType')
    ]


class ThreadSection(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    appearance: Annotated[
        ThreadSectionAppearance | None,
        Field(description='Optional appearance synchronized across clients.'),
    ] = None
    id: Annotated[
        str,
        Field(
            description='Opaque UUIDv7 identity that remains stable when the section is renamed.'
        ),
    ]
    name: Annotated[str, Field(description='The current user-visible section name.')]


class ThreadStatus1(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: Annotated[Literal['notLoaded'], Field(title='NotLoadedThreadStatusType')]


class ThreadStatus2(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: Annotated[Literal['idle'], Field(title='IdleThreadStatusType')]


class ThreadStatus3(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: Annotated[Literal['systemError'], Field(title='SystemErrorThreadStatusType')]


class ThreadStatus4(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    activeFlags: list[Literal['waitingOnApproval', 'waitingOnUserInput']]
    type: Annotated[Literal['active'], Field(title='ActiveThreadStatusType')]


class TokenUsageBreakdown(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    cacheWriteInputTokens: int | None = 0
    cachedInputTokens: int
    inputTokens: int
    outputTokens: int
    reasoningOutputTokens: int
    totalTokens: int


class WebSearchAction1(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    queries: list[str] | None = None
    query: str | None = None
    type: Annotated[Literal['search'], Field(title='SearchWebSearchActionType')]


class WebSearchAction2(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: Annotated[Literal['openPage'], Field(title='OpenPageWebSearchActionType')]
    url: str | None = None


class WebSearchAction3(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    pattern: str | None = None
    type: Annotated[Literal['findInPage'], Field(title='FindInPageWebSearchActionType')]
    url: str | None = None


class WebSearchAction4(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: Annotated[Literal['other'], Field(title='OtherWebSearchActionType')]


class ToolRequestUserInputOption(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    description: str
    label: str


class ToolRequestUserInputQuestion(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    header: str
    id: str
    isOther: bool | None = False
    isSecret: bool | None = False
    options: list[ToolRequestUserInputOption] | None = None
    question: str


class ToolRequestUserInputAnswer(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    answers: list[str]


class ToolRequestUserInputResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    answers: dict[str, ToolRequestUserInputAnswer]


class InitializeResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    codexHome: Annotated[
        str, Field(description="Absolute path to the server's $CODEX_HOME directory.")
    ]
    platformFamily: Annotated[
        str,
        Field(
            description='Platform family for the running app-server target, for example `"unix"` or `"windows"`.'
        ),
    ]
    platformOs: Annotated[
        str,
        Field(
            description='Operating system for the running app-server target, for example `"macos"`, `"linux"`, or `"windows"`.'
        ),
    ]
    userAgent: str


class NetworkPolicyAmendment(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    action: Literal['allow', 'deny']
    host: str


class FunctionCallOutputContentItem2(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    detail: Literal['auto', 'low', 'high', 'original'] | None = None
    image_url: str
    type: Annotated[
        Literal['input_image'],
        Field(title='InputImageFunctionCallOutputContentItemType'),
    ]


class ThreadStartParams(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    approvalPolicy: (
        Literal['untrusted', 'on-request', 'never'] | AskForApproval1 | None
    ) = None
    approvalsReviewer: Annotated[
        Literal['user', 'auto_review', 'guardian_subagent'] | None,
        Field(
            description='Override where approval requests are routed for review on this thread and subsequent turns.'
        ),
    ] = None
    baseInstructions: str | None = None
    config: dict[str, Any] | None = None
    cwd: str | None = None
    developerInstructions: str | None = None
    ephemeral: bool | None = None
    model: str | None = None
    modelProvider: str | None = None
    personality: Literal['none', 'friendly', 'pragmatic'] | None = None
    sandbox: Literal['read-only', 'workspace-write', 'danger-full-access'] | None = None
    serviceName: str | None = None
    serviceTier: str | None = None
    sessionStartSource: Literal['startup', 'clear'] | None = None
    threadSource: Annotated[
        str | None,
        Field(
            description='Optional client-supplied analytics source classification for this thread.'
        ),
    ] = None


class ApplyNetworkPolicyAmendment(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    network_policy_amendment: NetworkPolicyAmendment


class CommandExecutionApprovalDecision2(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    applyNetworkPolicyAmendment: ApplyNetworkPolicyAmendment


class FileSystemPath3(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: Annotated[Literal['special'], Field(title='SpecialFileSystemPathType')]
    value: (
        FileSystemSpecialPath1
        | FileSystemSpecialPath2
        | FileSystemSpecialPath3
        | FileSystemSpecialPath4
        | FileSystemSpecialPath5
        | FileSystemSpecialPath6
    )


class FileSystemSandboxEntry(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    access: Literal['read', 'write', 'deny']
    path: FileSystemPath1 | FileSystemPath2 | FileSystemPath3


class NetworkApprovalContext(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    host: str
    protocol: Literal['http', 'https', 'socks5Tcp', 'socks5Udp']


class CommandExecutionRequestApprovalParams(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    approvalId: Annotated[
        str | None,
        Field(
            description='Unique identifier for this specific approval callback.\n\nFor regular shell/unified_exec approvals, this is null.\n\nFor zsh-exec-bridge subcommand approvals, multiple callbacks can belong to one parent `itemId`, so `approvalId` is a distinct opaque callback id (a UUID) used to disambiguate routing. Stdin approvals also use a distinct callback id; inspect `kind` to distinguish them.'
        ),
    ] = None
    command: Annotated[str | None, Field(description='The command to be executed.')] = (
        None
    )
    commandActions: Annotated[
        list[CommandAction1 | CommandAction2 | CommandAction3 | CommandAction4] | None,
        Field(description='Best-effort parsed command actions for friendly display.'),
    ] = None
    cwd: Annotated[
        str | None, Field(description="The command's working directory.")
    ] = None
    environmentId: Annotated[
        str | None, Field(description='Environment in which the command will run.')
    ] = None
    itemId: str
    kind: Annotated[
        Literal['command', 'writeStdin'] | None,
        Field(
            description='Kind of action under review. Defaults to `command` for older servers.'
        ),
    ] = 'command'
    networkApprovalContext: Annotated[
        NetworkApprovalContext | None,
        Field(description='Optional context for a managed-network approval prompt.'),
    ] = None
    proposedExecpolicyAmendment: Annotated[
        list[str] | None,
        Field(
            description='Optional proposed execpolicy amendment to allow similar commands without prompting.'
        ),
    ] = None
    proposedNetworkPolicyAmendments: Annotated[
        list[NetworkPolicyAmendment] | None,
        Field(
            description='Optional proposed network policy amendments (allow/deny host) for future requests.'
        ),
    ] = None
    reason: Annotated[
        str | None,
        Field(
            description='Optional explanatory reason (e.g. request for network access).'
        ),
    ] = None
    startedAtMs: Annotated[
        int,
        Field(
            description='Unix timestamp (in milliseconds) when this approval request started.'
        ),
    ]
    threadId: str
    turnId: str


class CommandExecutionRequestApprovalResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    decision: (
        Literal['accept']
        | Literal['acceptForSession']
        | CommandExecutionApprovalDecision1
        | CommandExecutionApprovalDecision2
        | Literal['decline']
        | Literal['cancel']
    )


class ActiveTurnNotSteerable(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    turnKind: Literal['review', 'compact']


class CodexErrorInfo5(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    activeTurnNotSteerable: ActiveTurnNotSteerable


class CollabAgentState(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    message: str | None = None
    status: Literal[
        'pendingInit',
        'running',
        'interrupted',
        'completed',
        'errored',
        'shutdown',
        'notFound',
    ]


class FileUpdateChange(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    diff: str
    kind: PatchChangeKind1 | PatchChangeKind2 | PatchChangeKind3
    path: str


class MemoryCitation(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    entries: list[MemoryCitationEntry]
    threadIds: list[str]


class MisalignmentErrorDetails(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    detailedExplanation: Annotated[
        str | None,
        Field(
            description='A substantive localized explanation is required before offering continuation.'
        ),
    ] = None
    errorType: Annotated[
        str | None,
        Field(
            description='Open-ended classification; clients must accept categories added by Responses.'
        ),
    ] = None
    steer: Annotated[
        MisalignmentSteer | None,
        Field(
            description="Instruction to submit as the next turn's user input if continuation is confirmed."
        ),
    ] = None


class RateLimitSnapshot(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    credits: CreditsSnapshot | None = None
    individualLimit: SpendControlLimitSnapshot | None = None
    limitId: str | None = None
    limitName: str | None = None
    planType: (
        Literal[
            'free',
            'go',
            'plus',
            'pro',
            'prolite',
            'team',
            'self_serve_business_prolite',
            'self_serve_business_usage_based',
            'business',
            'ent26',
            'enterprise_cbp_automation',
            'enterprise_cbp_usage_based',
            'enterprise',
            'edu',
            'edu_plus',
            'edu_pro',
            'unknown',
        ]
        | None
    ) = None
    primary: RateLimitWindow | None = None
    rateLimitReachedType: (
        Literal[
            'rate_limit_reached',
            'workspace_owner_credits_depleted',
            'workspace_member_credits_depleted',
            'workspace_owner_usage_limit_reached',
            'workspace_member_usage_limit_reached',
        ]
        | None
    ) = None
    secondary: RateLimitWindow | None = None
    spendControlReached: Annotated[
        bool | None,
        Field(
            description='Backend-reported spend-control state. `None` is unavailable, not a sparse-update recovery.'
        ),
    ] = None


class SessionSource2(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    subAgent: (
        Literal['review', 'compact', 'memory_consolidation']
        | SubAgentSource1
        | SubAgentSource2
    )


class ThreadItem3(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    delivery: Literal['async'] | None = None
    id: str
    memoryCitation: MemoryCitation | None = None
    phase: Literal['commentary'] | Literal['final_answer'] | None = None
    questions: list[AsyncUserInputQuestion] | None = None
    text: str
    type: Annotated[Literal['agentMessage'], Field(title='AgentMessageThreadItemType')]


class ThreadItem8(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    changes: list[FileUpdateChange]
    id: str
    status: Literal['inProgress', 'completed', 'failed', 'declined']
    type: Annotated[Literal['fileChange'], Field(title='FileChangeThreadItemType')]


class ThreadItem11(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    agentsStates: Annotated[
        dict[str, CollabAgentState],
        Field(description='Last known status of the target agents, when available.'),
    ]
    id: Annotated[
        str, Field(description='Unique identifier for this collab tool call.')
    ]
    model: Annotated[
        str | None,
        Field(description='Model requested for the spawned agent, when applicable.'),
    ] = None
    prompt: Annotated[
        str | None,
        Field(
            description='Prompt text sent as part of the collab tool call, when available.'
        ),
    ] = None
    reasoningEffort: Annotated[
        ReasoningEffort | None,
        Field(
            description='Reasoning effort requested for the spawned agent, when applicable.'
        ),
    ] = None
    receiverThreadIds: Annotated[
        list[str],
        Field(
            description='Thread ID of the receiving agent, when applicable. In case of spawn operation, this corresponds to the newly spawned agent.'
        ),
    ]
    senderThreadId: Annotated[
        str, Field(description='Thread ID of the agent issuing the collab request.')
    ]
    status: Annotated[
        Literal['inProgress', 'completed', 'failed', 'interrupted'],
        Field(description='Current status of the collab tool call.'),
    ]
    tool: Annotated[
        Literal[
            'spawnAgent',
            'sendInput',
            'resumeAgent',
            'wait',
            'closeAgent',
            'sendMessage',
            'followupTask',
            'interruptAgent',
            'listAgents',
        ],
        Field(description='Name of the collab tool that was invoked.'),
    ]
    type: Annotated[
        Literal['collabAgentToolCall'], Field(title='CollabAgentToolCallThreadItemType')
    ]


class ThreadItem13(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    action: (
        WebSearchAction1 | WebSearchAction2 | WebSearchAction3 | WebSearchAction4 | None
    ) = None
    id: str
    query: str
    results: Annotated[
        list[Any] | None,
        Field(
            description='Structured search results returned out-of-band by standalone web search.\n\nThese stay as opaque JSON at the extension/app-server boundary so new result fields and result types can pass through without a Codex release.'
        ),
    ] = None
    type: Annotated[Literal['webSearch'], Field(title='WebSearchThreadItemType')]


class ThreadTokenUsage(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    last: TokenUsageBreakdown
    modelContextWindow: int | None = None
    total: TokenUsageBreakdown


class ThreadTokenUsageUpdatedNotification(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    threadId: str
    tokenUsage: ThreadTokenUsage
    turnId: str


class TurnError(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    additionalDetails: str | None = None
    codexErrorInfo: (
        Literal[
            'contextWindowExceeded',
            'sessionBudgetExceeded',
            'usageLimitExceeded',
            'rateLimitExceeded',
            'serverOverloaded',
            'cyberPolicy',
            'misalignmentPolicyViolation',
            'internalServerError',
            'unauthorized',
            'badRequest',
            'threadRollbackFailed',
            'sandboxError',
            'other',
        ]
        | CodexErrorInfo1
        | CodexErrorInfo2
        | CodexErrorInfo3
        | CodexErrorInfo4
        | CodexErrorInfo5
        | None
    ) = None
    message: str
    misalignment: Annotated[
        MisalignmentErrorDetails | None,
        Field(
            description='Optional public explanation and continuation instruction for a misalignment block.'
        ),
    ] = None


class ToolRequestUserInputParams(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    autoResolutionMs: Annotated[
        int | None,
        Field(
            description='@deprecated Use `isBlocking` to decide whether the request should block.',
            ge=0,
        ),
    ] = None
    isBlocking: bool
    itemId: str
    questions: list[ToolRequestUserInputQuestion]
    threadId: str
    turnId: str


class TurnToolOutput(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    name: str
    namespace: str | None = None
    output: (
        str
        | list[
            FunctionCallOutputContentItem1
            | FunctionCallOutputContentItem2
            | FunctionCallOutputContentItem3
            | FunctionCallOutputContentItem4
        ]
    )


class AdditionalFileSystemPermissions(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    entries: list[FileSystemSandboxEntry] | None = None
    globScanMaxDepth: Annotated[int | None, Field(ge=1)] = None
    read: Annotated[
        list[str] | None,
        Field(description='This will be removed in favor of `entries`.'),
    ] = None
    write: Annotated[
        list[str] | None,
        Field(description='This will be removed in favor of `entries`.'),
    ] = None


class RequestPermissionProfile(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    fileSystem: AdditionalFileSystemPermissions | None = None
    network: AdditionalNetworkPermissions | None = None


class PermissionsRequestApprovalParams(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    cwd: Annotated[
        str,
        Field(
            description='A path that is guaranteed to be absolute and normalized (though it is not guaranteed to be canonicalized or exist on the filesystem).\n\nIMPORTANT: When deserializing an `AbsolutePathBuf`, a base path must be set using [AbsolutePathBufGuard::new]. If no base path is set, the deserialization will fail unless the path being deserialized is already absolute.'
        ),
    ]
    environmentId: str | None = None
    itemId: str
    permissions: RequestPermissionProfile
    reason: str | None = None
    startedAtMs: Annotated[
        int,
        Field(
            description='Unix timestamp (in milliseconds) when this approval request started.'
        ),
    ]
    threadId: str
    turnId: str


class GrantedPermissionProfile(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    fileSystem: AdditionalFileSystemPermissions | None = None
    network: AdditionalNetworkPermissions | None = None


class PermissionsRequestApprovalResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    permissions: GrantedPermissionProfile
    scope: Literal['turn', 'session'] | None = 'turn'
    strictAutoReview: Annotated[
        bool | None,
        Field(
            description='Review every subsequent command in this turn before normal sandboxed execution.'
        ),
    ] = None


class AccountRateLimitsUpdatedNotification(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    rateLimits: RateLimitSnapshot


class ErrorNotification(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    error: TurnError
    threadId: str
    turnId: str
    willRetry: bool


class ThreadItem4(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    id: str
    name: str
    namespace: str | None = None
    output: (
        str
        | list[
            FunctionCallOutputContentItem1
            | FunctionCallOutputContentItem2
            | FunctionCallOutputContentItem3
            | FunctionCallOutputContentItem4
        ]
    )
    type: Annotated[
        Literal['functionCallOutput'], Field(title='FunctionCallOutputThreadItemType')
    ]


class Turn(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    completedAt: Annotated[
        int | None,
        Field(description='Unix timestamp (in seconds) when the turn completed.'),
    ] = None
    durationMs: Annotated[
        int | None,
        Field(
            description='Duration between turn start and completion in milliseconds, if known.'
        ),
    ] = None
    error: Annotated[
        TurnError | None,
        Field(description="Only populated when the Turn's status is failed."),
    ] = None
    id: Annotated[
        str,
        Field(
            description='Identifier for this turn. Codex-generated turn IDs are UUIDv7.'
        ),
    ]
    items: Annotated[
        list[
            ThreadItem1
            | ThreadItem2
            | ThreadItem3
            | ThreadItem4
            | ThreadItem5
            | ThreadItem6
            | ThreadItem7
            | ThreadItem8
            | ThreadItem9
            | ThreadItem10
            | ThreadItem11
            | ThreadItem12
            | ThreadItem13
            | ThreadItem14
            | ThreadItem15
            | ThreadItem16
            | ThreadItem17
            | ThreadItem18
            | ThreadItem19
        ],
        Field(description='Thread items currently included in this turn payload.'),
    ]
    itemsView: Annotated[
        Literal['notLoaded'] | Literal['summary'] | Literal['full'] | None,
        Field(
            description='Describes how much of `items` has been loaded for this turn.'
        ),
    ] = 'full'
    startedAt: Annotated[
        int | None,
        Field(description='Unix timestamp (in seconds) when the turn started.'),
    ] = None
    status: Literal['completed', 'interrupted', 'failed', 'inProgress']


class TurnCompletedNotification(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    threadId: str
    turn: Turn


class TurnStartedNotification(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    threadId: str
    turn: Turn


class TurnStartResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    turn: Turn


class TurnStartParams(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    approvalPolicy: Annotated[
        Literal['untrusted', 'on-request', 'never'] | AskForApproval1 | None,
        Field(
            description='Override the approval policy for this turn and subsequent turns.'
        ),
    ] = None
    approvalsReviewer: Annotated[
        Literal['user', 'auto_review', 'guardian_subagent'] | None,
        Field(
            description='Override where approval requests are routed for review on this turn and subsequent turns.'
        ),
    ] = None
    clientUserMessageId: str | None = None
    cwd: Annotated[
        str | None,
        Field(
            description='Override the working directory for this turn and subsequent turns.'
        ),
    ] = None
    effort: Annotated[
        ReasoningEffort | None,
        Field(
            description='Override the reasoning effort for this turn and subsequent turns.'
        ),
    ] = None
    input: list[
        UserInput1
        | UserInput2
        | UserInput3
        | UserInput4
        | UserInput5
        | UserInput6
        | UserInput7
    ]
    model: Annotated[
        str | None,
        Field(description='Override the model for this turn and subsequent turns.'),
    ] = None
    outputSchema: Annotated[
        Any | None,
        Field(
            description='Optional JSON Schema used to constrain the final assistant message for this turn.'
        ),
    ] = None
    personality: Annotated[
        Literal['none', 'friendly', 'pragmatic'] | None,
        Field(
            description='Override the personality for this turn and subsequent turns.'
        ),
    ] = None
    sandboxPolicy: Annotated[
        SandboxPolicy1 | SandboxPolicy2 | SandboxPolicy3 | SandboxPolicy4 | None,
        Field(
            description='Override the sandbox policy for this turn and subsequent turns.'
        ),
    ] = None
    serviceTier: Annotated[
        str | None,
        Field(
            description='Override the service tier for this turn and subsequent turns.'
        ),
    ] = None
    serviceTierForTurn: Annotated[
        str | None,
        Field(
            description='Override the service tier only when this request starts a new turn. Use "default" for standard speed. Omitted or null inherits the thread\'s tier. Does not change the thread\'s tier or a turn being steered.'
        ),
    ] = None
    summary: Annotated[
        Literal['auto', 'concise', 'detailed'] | Literal['none'] | None,
        Field(
            description='Override the reasoning summary for this turn and subsequent turns.'
        ),
    ] = None
    threadId: str
    toolOutput: TurnToolOutput | None = None
    turnTrigger: Annotated[
        str | None,
        Field(
            description='Optional source classification for the caller that starts this turn. Ignored when this request steers an already-active turn.'
        ),
    ] = None


class ItemCompletedNotification(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    completedAtMs: Annotated[
        int,
        Field(
            description='Unix timestamp (in milliseconds) when this item lifecycle completed.'
        ),
    ]
    item: (
        ThreadItem1
        | ThreadItem2
        | ThreadItem3
        | ThreadItem4
        | ThreadItem5
        | ThreadItem6
        | ThreadItem7
        | ThreadItem8
        | ThreadItem9
        | ThreadItem10
        | ThreadItem11
        | ThreadItem12
        | ThreadItem13
        | ThreadItem14
        | ThreadItem15
        | ThreadItem16
        | ThreadItem17
        | ThreadItem18
        | ThreadItem19
    )
    threadId: str
    turnId: str


class ItemStartedNotification(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    item: (
        ThreadItem1
        | ThreadItem2
        | ThreadItem3
        | ThreadItem4
        | ThreadItem5
        | ThreadItem6
        | ThreadItem7
        | ThreadItem8
        | ThreadItem9
        | ThreadItem10
        | ThreadItem11
        | ThreadItem12
        | ThreadItem13
        | ThreadItem14
        | ThreadItem15
        | ThreadItem16
        | ThreadItem17
        | ThreadItem18
        | ThreadItem19
    )
    startedAtMs: Annotated[
        int,
        Field(
            description='Unix timestamp (in milliseconds) when this item lifecycle started.'
        ),
    ]
    threadId: str
    turnId: str


class Thread(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    agentNickname: Annotated[
        str | None,
        Field(
            description='Optional random unique nickname assigned to an AgentControl-spawned sub-agent.'
        ),
    ] = None
    agentRole: Annotated[
        str | None,
        Field(
            description='Optional role (agent_role) assigned to an AgentControl-spawned sub-agent.'
        ),
    ] = None
    cliVersion: Annotated[
        str, Field(description='Version of the CLI that created the thread.')
    ]
    createdAt: Annotated[
        int,
        Field(description='Unix timestamp (in seconds) when the thread was created.'),
    ]
    cwd: Annotated[str, Field(description='Working directory captured for the thread.')]
    ephemeral: Annotated[
        bool,
        Field(
            description='Whether the thread is ephemeral and should not be materialized on disk.'
        ),
    ]
    forkedFromId: Annotated[
        str | None,
        Field(
            description='Source thread id when this thread was created by forking another thread.'
        ),
    ] = None
    gitInfo: Annotated[
        GitInfo | None,
        Field(
            description='Optional Git metadata captured when the thread was created.'
        ),
    ] = None
    historyMode: Annotated[
        Literal['legacy', 'paginated'] | None,
        Field(
            description='Persisted thread history contract selected when this thread was created.'
        ),
    ] = 'legacy'
    id: Annotated[
        str,
        Field(
            description='Identifier for this thread. Codex-generated thread IDs are UUIDv7.'
        ),
    ]
    model: Annotated[
        str | None,
        Field(
            description='Current configured model when loaded, otherwise the latest persisted model. Null when unavailable. This is not per-turn execution telemetry.'
        ),
    ] = None
    modelProvider: Annotated[
        str,
        Field(
            description="Model provider used for this thread (for example, 'openai')."
        ),
    ]
    name: Annotated[
        str | None, Field(description='Optional user-facing thread title.')
    ] = None
    parentThreadId: Annotated[
        str | None,
        Field(
            description='The ID of the parent thread. This will only be set if this thread is a subagent.'
        ),
    ] = None
    path: Annotated[
        str | None, Field(description='[UNSTABLE] Path to the thread on disk.')
    ] = None
    preview: Annotated[
        str,
        Field(
            description='Usually the first user message in the thread, if available.'
        ),
    ]
    projectId: Annotated[
        str | None,
        Field(description='Canonical project assignment owned by app-server, if any.'),
    ]
    reasoningEffort: Annotated[
        ReasoningEffort | None,
        Field(
            description='Current configured reasoning effort when loaded, otherwise the latest persisted effort. Null when unset or unavailable. This is not per-turn execution telemetry.'
        ),
    ] = None
    recencyAt: Annotated[
        int | None,
        Field(
            description='Unix timestamp (in seconds) used for thread recency ordering.'
        ),
    ] = None
    section: Annotated[
        ThreadSection | None,
        Field(
            description='The independently persisted section selected for this thread, if any.'
        ),
    ] = None
    sectionEnteredAt: Annotated[
        int | None,
        Field(
            description='Unix timestamp in seconds when the thread entered its current section.'
        ),
    ] = None
    sessionId: Annotated[
        str,
        Field(
            description='Session id shared by threads that belong to the same session tree.'
        ),
    ]
    source: Annotated[
        Literal['cli', 'vscode', 'exec', 'appServer', 'unknown']
        | SessionSource1
        | SessionSource2,
        Field(
            description='Origin of the thread (CLI, VSCode, codex exec, codex app-server, etc.).'
        ),
    ]
    status: Annotated[
        ThreadStatus1 | ThreadStatus2 | ThreadStatus3 | ThreadStatus4,
        Field(description='Current runtime status for the thread.'),
    ]
    threadSource: Annotated[
        str | None,
        Field(description='Optional analytics source classification for this thread.'),
    ] = None
    turns: Annotated[
        list[Turn],
        Field(
            description='Only populated on `thread/resume`, `thread/rollback`, `thread/fork`, and `thread/read` (when `includeTurns` is true) responses. For all other responses and notifications returning a Thread, the turns field will be an empty list.'
        ),
    ]
    updatedAt: Annotated[
        int,
        Field(
            description='Unix timestamp (in seconds) when the thread was last updated.'
        ),
    ]


class ThreadResumeResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    approvalPolicy: Literal['untrusted', 'on-request', 'never'] | AskForApproval1
    approvalsReviewer: Annotated[
        Literal['user', 'auto_review', 'guardian_subagent'],
        Field(
            description='Reviewer currently used for approval requests on this thread.'
        ),
    ]
    cwd: Annotated[
        str,
        Field(
            description='A path that is guaranteed to be absolute and normalized (though it is not guaranteed to be canonicalized or exist on the filesystem).\n\nIMPORTANT: When deserializing an `AbsolutePathBuf`, a base path must be set using [AbsolutePathBufGuard::new]. If no base path is set, the deserialization will fail unless the path being deserialized is already absolute.'
        ),
    ]
    instructionSources: Annotated[
        list[str] | None,
        Field(
            description='Environment-native paths to instruction source files currently loaded for this thread.'
        ),
    ] = []
    itemsBackwardsCursor: Annotated[
        str | None,
        Field(
            description='Opaque cursor for hydrating paginated items backwards.\n\nPass this as `cursor` to `thread/items/list` with `sortDirection: "desc"`. The first page includes the item identified by the cursor.'
        ),
    ] = None
    model: str
    modelProvider: str
    reasoningEffort: ReasoningEffort | None = None
    sandbox: Annotated[
        SandboxPolicy1 | SandboxPolicy2 | SandboxPolicy3 | SandboxPolicy4,
        Field(
            description='Legacy sandbox policy retained for compatibility. Experimental clients should prefer `activePermissionProfile` for profile provenance.'
        ),
    ]
    serviceTier: str | None = None
    thread: Thread
    turnsBackwardsCursor: Annotated[
        str | None,
        Field(
            description='Opaque cursor for hydrating paginated turns backwards.\n\nPass this as `cursor` to `thread/turns/list` with `sortDirection: "desc"`. The first page includes the turn identified by the cursor.'
        ),
    ] = None


class ThreadStartResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    approvalPolicy: Literal['untrusted', 'on-request', 'never'] | AskForApproval1
    approvalsReviewer: Annotated[
        Literal['user', 'auto_review', 'guardian_subagent'],
        Field(
            description='Reviewer currently used for approval requests on this thread.'
        ),
    ]
    cwd: Annotated[
        str,
        Field(
            description='A path that is guaranteed to be absolute and normalized (though it is not guaranteed to be canonicalized or exist on the filesystem).\n\nIMPORTANT: When deserializing an `AbsolutePathBuf`, a base path must be set using [AbsolutePathBufGuard::new]. If no base path is set, the deserialization will fail unless the path being deserialized is already absolute.'
        ),
    ]
    instructionSources: Annotated[
        list[str] | None,
        Field(
            description='Environment-native paths to instruction source files currently loaded for this thread.'
        ),
    ] = []
    model: str
    modelProvider: str
    reasoningEffort: ReasoningEffort | None = None
    sandbox: Annotated[
        SandboxPolicy1 | SandboxPolicy2 | SandboxPolicy3 | SandboxPolicy4,
        Field(
            description='Legacy sandbox policy retained for compatibility. Experimental clients should prefer `activePermissionProfile` for profile provenance.'
        ),
    ]
    serviceTier: str | None = None
    thread: Thread


class CodexProtocolRoot(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    InitializeParams_1: Annotated[
        InitializeParams | None, Field(alias='InitializeParams')
    ] = None
    InitializeResponse_1: Annotated[
        InitializeResponse | None, Field(alias='InitializeResponse')
    ] = None
    ClientInfo_1: Annotated[ClientInfo | None, Field(alias='ClientInfo')] = None
    ThreadStartParams_1: Annotated[
        ThreadStartParams | None, Field(alias='ThreadStartParams')
    ] = None
    ThreadStartResponse_1: Annotated[
        ThreadStartResponse | None, Field(alias='ThreadStartResponse')
    ] = None
    ThreadResumeParams_1: Annotated[
        ThreadResumeParams | None, Field(alias='ThreadResumeParams')
    ] = None
    ThreadResumeResponse_1: Annotated[
        ThreadResumeResponse | None, Field(alias='ThreadResumeResponse')
    ] = None
    TurnStartParams_1: Annotated[
        TurnStartParams | None, Field(alias='TurnStartParams')
    ] = None
    TurnStartResponse_1: Annotated[
        TurnStartResponse | None, Field(alias='TurnStartResponse')
    ] = None
    TurnInterruptParams_1: Annotated[
        TurnInterruptParams | None, Field(alias='TurnInterruptParams')
    ] = None
    Thread_1: Annotated[Thread | None, Field(alias='Thread')] = None
    Turn_1: Annotated[Turn | None, Field(alias='Turn')] = None
    TurnStatus: Literal['completed', 'interrupted', 'failed', 'inProgress'] | None = (
        None
    )
    ThreadItem: (
        ThreadItem1
        | ThreadItem2
        | ThreadItem3
        | ThreadItem4
        | ThreadItem5
        | ThreadItem6
        | ThreadItem7
        | ThreadItem8
        | ThreadItem9
        | ThreadItem10
        | ThreadItem11
        | ThreadItem12
        | ThreadItem13
        | ThreadItem14
        | ThreadItem15
        | ThreadItem16
        | ThreadItem17
        | ThreadItem18
        | ThreadItem19
        | None
    ) = None
    ItemStartedNotification_1: Annotated[
        ItemStartedNotification | None, Field(alias='ItemStartedNotification')
    ] = None
    ItemCompletedNotification_1: Annotated[
        ItemCompletedNotification | None, Field(alias='ItemCompletedNotification')
    ] = None
    AgentMessageDeltaNotification_1: Annotated[
        AgentMessageDeltaNotification | None,
        Field(alias='AgentMessageDeltaNotification'),
    ] = None
    CommandExecutionOutputDeltaNotification_1: Annotated[
        CommandExecutionOutputDeltaNotification | None,
        Field(alias='CommandExecutionOutputDeltaNotification'),
    ] = None
    FileChangeOutputDeltaNotification_1: Annotated[
        FileChangeOutputDeltaNotification | None,
        Field(alias='FileChangeOutputDeltaNotification'),
    ] = None
    ReasoningSummaryTextDeltaNotification_1: Annotated[
        ReasoningSummaryTextDeltaNotification | None,
        Field(alias='ReasoningSummaryTextDeltaNotification'),
    ] = None
    TurnStartedNotification_1: Annotated[
        TurnStartedNotification | None, Field(alias='TurnStartedNotification')
    ] = None
    TurnCompletedNotification_1: Annotated[
        TurnCompletedNotification | None, Field(alias='TurnCompletedNotification')
    ] = None
    ThreadTokenUsageUpdatedNotification_1: Annotated[
        ThreadTokenUsageUpdatedNotification | None,
        Field(alias='ThreadTokenUsageUpdatedNotification'),
    ] = None
    AccountRateLimitsUpdatedNotification_1: Annotated[
        AccountRateLimitsUpdatedNotification | None,
        Field(alias='AccountRateLimitsUpdatedNotification'),
    ] = None
    ErrorNotification_1: Annotated[
        ErrorNotification | None, Field(alias='ErrorNotification')
    ] = None
    CommandExecutionRequestApprovalParams_1: Annotated[
        CommandExecutionRequestApprovalParams | None,
        Field(alias='CommandExecutionRequestApprovalParams'),
    ] = None
    CommandExecutionRequestApprovalResponse_1: Annotated[
        CommandExecutionRequestApprovalResponse | None,
        Field(alias='CommandExecutionRequestApprovalResponse'),
    ] = None
    FileChangeRequestApprovalParams_1: Annotated[
        FileChangeRequestApprovalParams | None,
        Field(alias='FileChangeRequestApprovalParams'),
    ] = None
    FileChangeRequestApprovalResponse_1: Annotated[
        FileChangeRequestApprovalResponse | None,
        Field(alias='FileChangeRequestApprovalResponse'),
    ] = None
    PermissionsRequestApprovalParams_1: Annotated[
        PermissionsRequestApprovalParams | None,
        Field(alias='PermissionsRequestApprovalParams'),
    ] = None
    PermissionsRequestApprovalResponse_1: Annotated[
        PermissionsRequestApprovalResponse | None,
        Field(alias='PermissionsRequestApprovalResponse'),
    ] = None
    ToolRequestUserInputParams_1: Annotated[
        ToolRequestUserInputParams | None, Field(alias='ToolRequestUserInputParams')
    ] = None
    ToolRequestUserInputResponse_1: Annotated[
        ToolRequestUserInputResponse | None, Field(alias='ToolRequestUserInputResponse')
    ] = None
